config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :scientists
  resources :missions
  resources :planets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :scientist
  belongs_to :planet

end

app/models/planet.rb
class Planet < ApplicationRecord
    has_many :missions
    has_many :scientists, through: :missions
end

app/models/scientist.rb
class Scientist < ApplicationRecord
    has_many :missions
    has_many :planets, through: :missions

    validates :name, uniqueness: true
    validates :field, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/missions_controller.rb
class MissionsController < ActionController::Base

    def index
        @missions = Mission.all
    end
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
    before_action :set_planet, only: [:show, :edit, :update, :destroy]
  
    # GET /planets
    # GET /planets.json
    def index
      @planets = Planet.all
    end
  
    # GET /planets/1
    # GET /planets/1.json
    def show
    end
  
    # GET /planets/new
    def new
      @planet = Planet.new
    end
  
    # GET /planets/1/edit
    def edit
    end
  
    # POST /planets
    # POST /planets.json
    def create
      @planet = Planet.new(planet_params)
  
      respond_to do |format|
        if @planet.save
          format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
          format.json { render :show, status: :created, location: @planet }
        else
          format.html { render :new }
          format.json { render json: @planet.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /planets/1
    # PATCH/PUT /planets/1.json
    def update
      respond_to do |format|
        if @planet.update(planet_params)
          format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
          format.json { render :show, status: :ok, location: @planet }
        else
          format.html { render :edit }
          format.json { render json: @planet.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /planets/1
    # DELETE /planets/1.json
    def destroy
      @planet.destroy
      respond_to do |format|
        format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_planet
        @planet = Planet.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def planet_params
        params.require(:planet).permit(:name, :distance_from_earth, :nearest_star)
      end
  end

app/controllers/scientists_controller.rb
class ScientistsController < ActionController::Base
    before_action :set_scientist, only: [:show, :edit, :update, :destroy]
    
    def index
        @scientists = Scientist.all
    end

    def show
    end

    def new
        @scientist = Scientist.new
    end
    
    def create
        @scientist = Scientist.new(scientist_params)

        if @scientist.valid?
            @scienitst.save
            redirect_to scientists_path
        else
            render :new
        end
    end


    def edit
    end

    def update
        if @scientist.update(scientist_params)
            redirect_to scientist_path(@scientist)
        else
            render :edit
        end
    end

    
    def destroy
        @scientist.destroy
        puts "#{@scientist.name} has been destroyed."
        redirect_to scientists_path
    end



    private

    def set_scientist
        @scientist = Scientist.find(params[:id])
    end

    def scientist_params
        params.require(:scientist).permit(:name, :field)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosmicTravel3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/scientists/_form.html.erb
<%= form_for @scientist do |f| %>
    <%= f.label :name%>
    <%= f.text_field :name%>
    </br>
    <%= f.label :field%>
    <%= f.text_field :field%>
    </br>
    <%= f.submit %>

<% end %>

app/views/scientists/index.html.erb
<h1>Scientist List</h1>

<% @scientists.each do |scientist| %>
    <%= link_to scientist.name, scientist_path(scientist) %></br>
<% end %>

<%= button_to "Create Scientist", new_scientist_path %>

app/views/scientists/new.html.erb
<h1>Create new Scientist</h1>

<%= render 'form' %>

app/views/scientists/show.html.erb
<h1>This is <%= @scientist.name %>'s page</h1>
<h3><%= @scientist.name %> works in <%= @scientist.field %></h3>

<h2> <%= @scientist.name %> has visited these planets</h2>